### PR TITLE
handlebars templates are mustache-mode, too!

### PR DESCRIPTION
**Pull request by bostonaholic**
added .hbs extensions to alist for mustache-mode

### CODE REVIEW

**Comment by reedlaw** [comment]
I'm interested in a Handlebars mode for Emacs. @bostonaholic have you made any progress?

**Comment by bostonaholic** [comment]
@reedlaw I've been wanting to fork the `mustache-mode` and make the proper additions to create a `handlebars-mode`. I've got a pending pull request to the `mustache-mode` project which allows for multi-line comments. I was waiting for that to get merged before forking again and creating a `handlebars-mode`.

**Comment by danielevans** [comment]
I've started some inroads towards a handlebars-mode based on mustache-mode. Any suggestions would be appreciated.

https://github.com/danielevans/handlebars-mode

**Comment by locks** [comment]
Seems like @danielevans's mode is still actively supported?
Anyone wanting handlebars should probably use it :) Thank you!

**Pull request closed without merging**
